apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h6beplgk5-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-187ee1c877.cpmk.p3.openshiftapps.com/rhtap/rhtap-qe:f311fe8cebee0af8c9154dd9cd1fad46b5ce5f4b@sha256:83f77f568df771b7aae80611d8ebfaba406f31a12defabf186d967fea9f0100d
          name: container-image
